import { Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Flag, LoaderCircle, MessageSquare, Star, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";
import { addComment, deleteComment, getComments, reportComment, type Comment } from "@/lib/comments.functions";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

export function CourseComments({ courseId }: { courseId: string }) {
  const get = useServerFn(getComments);
  const queryKey = ["comments", "course", courseId] as const;
  const { data: comments = [], isLoading } = useQuery({ queryKey, queryFn: () => get({ data: { targetId: courseId, targetType: "course" } }) });
  return <section className="mt-12 border-t border-border pt-10"><div className="flex items-center gap-2"><MessageSquare className="h-6 w-6 text-primary" /><h2 className="text-2xl font-bold text-foreground">التقييمات والتعليقات</h2></div><div className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-6"><RatingSummary comments={comments} /><AddCommentForm courseId={courseId} queryKey={queryKey} /></div><CommentList comments={comments} isLoading={isLoading} queryKey={queryKey} /></div></section>;
}

export function RatingSummary({ comments }: { comments: Comment[] }) {
  const average = comments.length ? comments.reduce((sum, comment) => sum + comment.rating, 0) / comments.length : 0;
  return <div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><p className="text-sm font-semibold text-foreground">ملخص التقييم</p><div className="mt-4 flex items-center gap-4"><strong className="text-5xl font-extrabold text-foreground">{average.toFixed(1)}</strong><div><Stars value={Math.round(average)} /><p className="mt-1 text-xs text-muted-foreground">من {comments.length} تقييم</p></div></div><div className="mt-5 space-y-2">{[5, 4, 3, 2, 1].map((rating) => { const count = comments.filter((comment) => comment.rating === rating).length; const percentage = comments.length ? (count / comments.length) * 100 : 0; return <div key={rating} className="flex items-center gap-2 text-xs"><span className="w-3">{rating}</span><Star className="h-3.5 w-3.5 fill-warning text-warning" /><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-warning" style={{ width: `${percentage}%` }} /></div><span className="w-5 text-left text-muted-foreground">{count}</span></div>; })}</div></div>;
}

export function AddCommentForm({ courseId, queryKey }: { courseId: string; queryKey: readonly string[] }) {
  const { user } = useAuth(); const queryClient = useQueryClient(); const add = useServerFn(addComment); const [rating, setRating] = useState(0); const [content, setContent] = useState("");
  const mutation = useMutation({ mutationFn: () => add({ data: { targetId: courseId, targetType: "course", rating, content } }), onSuccess: () => { setContent(""); setRating(0); queryClient.invalidateQueries({ queryKey }); toast.success("تم نشر تعليقك بنجاح."); }, onError: (error: unknown) => toast.error(error instanceof Error ? error.message : "تعذر نشر التعليق.") });
  return <div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h3 className="font-semibold text-foreground">أضف تقييمك</h3>{user ? <><p className="mt-2 text-sm text-muted-foreground">شارك تجربتك لمساعدة الآخرين.</p><div className="mt-4"><p className="mb-2 text-sm font-medium text-foreground">تقييمك</p><StarPicker value={rating} onChange={setRating} /></div><Textarea value={content} onChange={(event) => setContent(event.target.value)} className="mt-4 min-h-28" placeholder="اكتب رأيك في الدورة..." maxLength={1000} /><div className="mt-3 flex items-center justify-between"><span className="text-xs text-muted-foreground">{content.length}/1000</span><Button disabled={mutation.isPending || rating === 0 || content.trim().length < 2} onClick={() => mutation.mutate()}>{mutation.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />} نشر التعليق</Button></div></> : <div className="mt-4 rounded-xl bg-muted p-4 text-sm text-muted-foreground">يرجى <Link to="/login" className="font-bold text-primary hover:underline">تسجيل الدخول</Link> لإضافة تقييم.</div>}</div>;
}

export function CommentList({ comments, isLoading, queryKey }: { comments: Comment[]; isLoading: boolean; queryKey: readonly string[] }) {
  if (isLoading) return <div className="flex min-h-48 items-center justify-center rounded-2xl border border-border bg-card"><LoaderCircle className="h-6 w-6 animate-spin text-primary" /></div>;
  if (!comments.length) return <div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card p-6 text-center"><MessageSquare className="h-7 w-7 text-muted-foreground" /><p className="mt-3 font-semibold text-foreground">لا توجد تعليقات بعد</p><p className="mt-1 text-sm text-muted-foreground">كن أول من يشارك تجربته.</p></div>;
  return <div className="space-y-3">{comments.map((comment) => <CommentCard key={comment.id} comment={comment} queryKey={queryKey} />)}</div>;
}

export function CommentCard({ comment, queryKey }: { comment: Comment; queryKey: readonly string[] }) {
  const { user } = useAuth(); const queryClient = useQueryClient(); const del = useServerFn(deleteComment); const report = useServerFn(reportComment); const [confirmDelete, setConfirmDelete] = useState(false); const [reportOpen, setReportOpen] = useState(false); const [reason, setReason] = useState<"inappropriate" | "spam" | "hate" | "other">("inappropriate"); const [details, setDetails] = useState("");
  const canDelete = user?.id === comment.userId || user?.role === "admin";
  const deleteMutation = useMutation({ mutationFn: () => del({ data: { id: comment.id } }), onSuccess: () => { queryClient.invalidateQueries({ queryKey }); toast.success("تم حذف التعليق."); }, onError: (error: unknown) => toast.error(error instanceof Error ? error.message : "تعذر حذف التعليق.") });
  const reportMutation = useMutation({ mutationFn: () => report({ data: { commentId: comment.id, reason, details } }), onSuccess: () => { setReportOpen(false); toast.success("تم إرسال بلاغك بنجاح", { description: "سيتولى المراجعون فحص المحتوى." }); }, onError: (error: unknown) => toast.error(error instanceof Error ? error.message : "تعذر إرسال البلاغ.") });
  return <article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 font-bold text-primary">{comment.userName.slice(0, 1)}</div><div className="min-w-0"><p className="truncate font-semibold text-foreground">{comment.userName}</p><div className="mt-1 flex items-center gap-2"><Stars value={comment.rating} size="sm" /><span className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("ar", { dateStyle: "medium" }).format(new Date(comment.created))}</span></div></div></div><div className="flex shrink-0 gap-1">{user && user.id !== comment.userId && <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-destructive" onClick={() => setReportOpen(true)} aria-label="الإبلاغ عن تعليق"><Flag className="h-4 w-4" /></Button>}{canDelete && <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-destructive" onClick={() => setConfirmDelete(true)} aria-label="حذف التعليق"><Trash2 className="h-4 w-4" /></Button>}</div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-foreground">{comment.content}</p><AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>حذف التعليق</AlertDialogTitle><AlertDialogDescription>لا يمكن التراجع عن هذا الإجراء.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>إلغاء</AlertDialogCancel><AlertDialogAction onClick={() => deleteMutation.mutate()} className="bg-destructive text-destructive-foreground">حذف</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Dialog open={reportOpen} onOpenChange={setReportOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>الإبلاغ عن تعليق</DialogTitle><DialogDescription>اختر سبب البلاغ لمساعدة المراجعين.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-2">{([ ["inappropriate", "محتوى غير لائق"], ["spam", "إزعاج أو Spam"], ["hate", "كراهية أو إساءة"], ["other", "سبب آخر"] ] as const).map(([value, label]) => <Button key={value} type="button" variant={reason === value ? "default" : "outline"} onClick={() => setReason(value)}>{label}</Button>)}</div><Textarea value={details} onChange={(event) => setDetails(event.target.value)} placeholder="توضيح اختياري" maxLength={500} /><DialogFooter><Button disabled={reportMutation.isPending} onClick={() => reportMutation.mutate()}>{reportMutation.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />} إرسال البلاغ</Button></DialogFooter></DialogContent></Dialog></article>;
}

function Stars({ value, size = "md" }: { value: number; size?: "sm" | "md" }) { return <span className="flex gap-0.5" aria-label={`${value} من 5 نجوم`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`${size === "sm" ? "h-3.5 w-3.5" : "h-4 w-4"} ${index < value ? "fill-warning text-warning" : "text-muted-foreground/30"}`} />)}</span>; }
function StarPicker({ value, onChange }: { value: number; onChange: (rating: number) => void }) { return <div className="flex gap-1" dir="ltr">{Array.from({ length: 5 }, (_, index) => <button key={index} type="button" onClick={() => onChange(index + 1)} className="rounded p-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" aria-label={`${index + 1} نجوم`}><Star className={`h-7 w-7 transition-colors ${index < value ? "fill-warning text-warning" : "text-muted-foreground/40 hover:text-warning"}`} /></button>)}</div>; }
